apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-e78i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-e78i
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-e78i
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-e78i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-e78i
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qamg-tenant/rhtap-demo-app/hacbs-test-project-e78i@sha256:ab1c296c0c08b09ec75562849db7f3d0d048e382c26a3c136b7586170632f847
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
